LVH.Lesson04/Models/LVHCustomer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LVH.Lesson04.Models
{
    public class LVHCustomer
    {
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public int YearOfBirth { get; set; }
    }
}

LVH.Lesson04/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LVH.Lesson04.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LVH.Lesson04/Controllers/LVHCustomerController.cs
using LVH.Lesson04.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LVH.Lesson04.Controllers
{
    public class LVHCustomerController : Controller
    {
        // GET: LVHCustomer
        public ActionResult Index()
        {
            return View();
        }
        //Action: LVHCustomerDetail
        public ActionResult LVHCustomerDetail()
        {
            //tạo đối tượng dữ liệu
            var customer = new LVHCustomer()
            {
                CustomerID = 1,
                FirstName = "Lê Vinh",
                LastName = "Huy",
                Address = "K22CNT1",
                YearOfBirth = 2004
            };
            ViewBag.customer = customer;

            return View();
        }
        public ActionResult LVHListCustomer()
        {
            var list = new List<LVHCustomer>()
            {
                new LVHCustomer()
                {
                    CustomerID = 1,
                    FirstName = "Lê Vinh",
                    LastName = "Huy",
                    Address = "K22CNT1",
                    YearOfBirth = 2004
                },
                new LVHCustomer()
                {
                    CustomerID = 2,
                    FirstName = "Lê Vinh",
                    LastName = "Huy 2",
                    Address = "K22CNT1",
                    YearOfBirth = 2004
                },
                new LVHCustomer()
                {
                    CustomerID = 3,
                    FirstName = "Lê Vinh",
                    LastName = "Huy 3",
                    Address = "K22CNT1",
                    YearOfBirth = 2004
                },
                new LVHCustomer()
                {
                    CustomerID = 4,
                    FirstName = "Lê Vinh",
                    LastName = "Huy 4",
                    Address = "K22CNT1",
                    YearOfBirth = 2004
                },
            };
            //ViewBag.list = list; //đưa dữ liệu ra view bằng đối tượng viewbag
            return View(list);

        }
    }
}

LVH.Lesson04/Controllers/LVHCustomerScaffoldingController.cs
using LVH.Lesson04.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LVH.Lesson04.Controllers
{
    public class LVHCustomerScaffoldingController : Controller
    {
        //mốc data
        private static List<LVHCustomer> listCutomer = new List<LVHCustomer>()
            {
                new LVHCustomer()
                {
                    CustomerID = 1,
                    FirstName = "Lê Vinh",
                    LastName = "Huy",
                    Address = "K22CNT1",
                    YearOfBirth = 2004
                },
                new LVHCustomer()
                {
                    CustomerID = 2,
                    FirstName = "Lê Vinh",
                    LastName = "Huy 2",
                    Address = "K22CNT1",
                    YearOfBirth = 2004
                },
                new LVHCustomer()
                {
                    CustomerID = 3,
                    FirstName = "Lê Vinh",
                    LastName = "Huy 3",
                    Address = "K22CNT1",
                    YearOfBirth = 2004
                },
                new LVHCustomer()
                {
                    CustomerID = 4,
                    FirstName = "Lê Vinh",
                    LastName = "Huy 4",
                    Address = "K22CNT1",
                    YearOfBirth = 2004
                },
            };
        // GET: LVHCustomerScaffolding
        //listcustomer
        public ActionResult Index()
        {
            return View(listCutomer);
        }
        [HttpGet]
        public ActionResult LVHCreate()
        {
            var model = new LVHCustomer();
            return View();
        }
        [HttpPost]
        public ActionResult LVHCreate(LVHCustomer model)
        {
            //Thêm mới đối tượng khách hàng vào ds dữ liệu
            listCutomer.Add(model);
            //return View();
            //chuyển về trang danh sách
            return RedirectToAction("Index");
        }
        public ActionResult LVHEdit(int id)
        {
            var customer = listCutomer.FirstOrDefault(x => x.CustomerID == id);
            return View(customer);
        }
        public ActionResult LVHDetails(int id)
        {
            var customer = listCutomer.FirstOrDefault(s => s.CustomerID == id);
            return View(customer);
        }
    }
}

LVH.Lesson04/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

LVH.Lesson04/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

LVH.Lesson04/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

LVH.Lesson04/Views/LVHCustomer/LVHCustomerDetail.cshtml
@{
    ViewBag.Title = "Thông tin khách hàng";
}

<h2>Thông tin khách hàng</h2>

<div class="alert alert-danger">
    <h3>Mã số: @ViewBag.customer.CustomerID</h3>
    <p>Họ và tên: @ViewBag.customer.FirstName @ViewBag.customer.LastName</p>
    <p>Lớp: @ViewBag.customer.Address</p>
    <p>Năm sinh: @ViewBag.customer.YearOfBirth</p>

</div>

LVH.Lesson04/Views/LVHCustomer/LVHListCustomer.cshtml
@{
    ViewBag.Title = "Danh sách khách hàng";
    //var list = ViewBag.list;
    //var list = Model as List<LVH.Lesson04.Models.LVHCustomer>
    int stt = 0;
}

<h2>Danh sách khách hàng</h2>
<div class="row">
    <table class="table talbe-border">
        <thead>
            <tr>
                <th>#</th>
                <th>Mã số</th>
                <th>Họ và Tên</th>
                <th>Địa chỉ</th>
                <th>Năm sinh</th>
                <th>Chức năng</th>
            </tr>
        </thead>
        <tbody>
            @*@foreach (var item in list)*@
            @foreach (var item in Model)
            {
                stt++;
                <tr>
                    <td>@stt</td>
                    <td>@item.CustomerID</td>
                    <td>@item.FirstName @item.LastName</td>
                    <td>@item.Address</td>
                    <td>@item.YearOfBirth</td>
                    <td>
                        <a href="#">Edit</a>
                        <a href="#">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

LVH.Lesson04/Views/LVHCustomerScaffolding/Index.cshtml
@model IEnumerable<LVH.Lesson04.Models.LVHCustomer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "LVHCreate")
</p>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearOfBirth)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearOfBirth)
        </td>
        <td>
            @Html.ActionLink("Edit", "LVHEdit", new { id=item.CustomerID}) |
            @Html.ActionLink("Details", "Details", new { id = item.CustomerID }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

LVH.Lesson04/Views/LVHCustomerScaffolding/LVHCreate.cshtml
@model LVH.Lesson04.Models.LVHCustomer

@{
    ViewBag.Title = "LVHCreate";
}

<h2>LVHCreate</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LVHCustomer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LVH.Lesson04/Views/LVHCustomerScaffolding/LVHDetails.cshtml
@model LVH.Lesson04.Models.LVHCustomer

@{
    ViewBag.Title = "LVHDetails";
}

<h2>LVHDetails</h2>

<div>
    <h4>LVHCustomer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearOfBirth)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CustomerID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LVH.Lesson04/Views/LVHCustomerScaffolding/LVHEdit.cshtml
@model LVH.Lesson04.Models.LVHCustomer

@{
    ViewBag.Title = "LVHEdit";
}

<h2>LVHEdit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LVHCustomer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LVH.Lesson04/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("CustomerDetail", "LVHCustomerDetail", "LVHCustomer")</li>
                    <li>@Html.ActionLink("List Customer", "LVHListCustomer", "LVHCustomer")</li>
                    <li>@Html.ActionLink("List Customer Scaffolding", "Index", "LVHCustomerScaffolding")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>